### ISSUE TITLE
Cdc 

### ISSUE THREAD

**Issue by gedw99** [cms103/jetstream-outbox#1]
I get that it pops the message into the db and then nats but I was wondering if there is the ability to use this facility to replicate postresql data between postresql servers too ?

byw it’s nice and straight to the point code .

**Comment by cms103** [comment]
Yes, it's possible, however I'm not sure what benefit you'd get beyond the standard Postgres replication tools. It's the DB replication infrastructure that allows this technique to work and the existing tooling is going to be much more mature.

**Comment by gedw99** [comment]
Makes sense now.

there is a nats based oh replication system so it would be cool to use that since nats is doing the outbox system too.

Here is one for SQLite that uses nats so just need to adapt for postresql.

https://github.com/maxpert/marmot
